---
 - name: install the required packages for NFS
   action: apt package={{item}} state=installed
   with_items:
   - nfs-kernel-server
   - nfs-common

 - name: create shared directory for NFS
   file: path=/share state=directory mode=777 owner=root group=root

 - name: NFS config file
   action: template src=exports.j2 dest=/etc/exports

 - name: rpcbind is running
   action: service name=rpcbind state=started enabled=yes

 - name: NFS is running
   action: service name=nfs-kernel-server state=started enabled=yes

 - name: exportfs
   action: command exportfs -a