---
 - name: shared directory for nfs
   file: path=/share state=directory mode=777 owner=root group=root

 - name: mount the share on the remote
   action: command mount {{groups.master}}:/share /share
