---
 - name: install the required packages for OpenMPI
   action: apt package={{item}} state=installed
   with_items:
   - openmpi-bin 
   - openmpi-checkpoint
   - openmpi-common
   - openmpi-doc 
   - libopenmpi-dev

 - name: enable openmpi service at boot
   service: name=openmpi-bin enabled=yes

  # - name: restart openmpi
  #   service: name=openmpi-bin state=restarted

